import { VpsPlan, DealPlan, Feedback, FaqItem, OsDistro, Partner, BenchmarkItem } from './types';

export const HOT_DEALS: DealPlan[] = [
  {
    id: 'deal-gold-1',
    name: 'VPS Gold Deal 1',
    badge: 'Tiết kiệm 34%',
    cpu: '1 vCPU Intel Gold',
    ram: '1 GB DDR4 ECC',
    disk: '20 GB NVMe U.2 Enterprise',
    bandwidth: 'Không giới hạn (100 Mbps)',
    ipv4: '01 IPv4 Riêng',
    priceMonthly: 59000,
    priceOriginal: 89000,
    discountPercent: 34,
    orderUrl: 'https://id.thuevpsgiare.vn/store/special-deal-2025',
    stockStatus: 'Sẵn sàng kích hoạt tự động',
  },
  {
    id: 'deal-gold-2',
    name: 'VPS Gold Deal 2',
    badge: 'Bán chạy',
    cpu: '2 vCPU Intel Gold',
    ram: '2 GB DDR4 ECC',
    disk: '30 GB NVMe U.2 Enterprise',
    bandwidth: 'Không giới hạn (100 Mbps)',
    ipv4: '01 IPv4 Riêng',
    priceMonthly: 109000,
    priceOriginal: 159000,
    discountPercent: 31,
    orderUrl: 'https://id.thuevpsgiare.vn/store/special-deal-2025',
    stockStatus: 'Sẵn sàng kích hoạt tự động',
  },
  {
    id: 'deal-gold-3',
    name: 'VPS Gold Deal 3',
    badge: 'Hiệu năng cao',
    cpu: '4 vCPU Intel Gold',
    ram: '4 GB DDR4 ECC',
    disk: '50 GB NVMe U.2 Enterprise',
    bandwidth: 'Không giới hạn (100 Mbps)',
    ipv4: '01 IPv4 Riêng',
    priceMonthly: 199000,
    priceOriginal: 299000,
    discountPercent: 33,
    orderUrl: 'https://id.thuevpsgiare.vn/store/special-deal-2025',
    stockStatus: 'Sẵn sàng kích hoạt tự động',
  },
  {
    id: 'deal-gold-4',
    name: 'VPS Gold Deal 4',
    badge: 'Cấu hình khủng',
    cpu: '6 vCPU Intel Gold',
    ram: '8 GB DDR4 ECC',
    disk: '80 GB NVMe U.2 Enterprise',
    bandwidth: 'Không giới hạn (100 Mbps)',
    ipv4: '01 IPv4 Riêng',
    priceMonthly: 389000,
    priceOriginal: 560000,
    discountPercent: 31,
    orderUrl: 'https://id.thuevpsgiare.vn/store/special-deal-2025',
    stockStatus: 'Sẵn sàng kích hoạt tự động',
  },
];

export const VPS_PLANS: VpsPlan[] = [
  {
    id: 'vps-gold-1',
    name: 'VPS Gold 1',
    cpu: '1 vCPU Intel Gold',
    ram: '1 GB RAM DDR4 ECC',
    disk: '20 GB SSD NVMe U.2',
    bandwidth: 'Unlimited Bandwidth',
    ipv4: '01 IPv4 Riêng',
    priceMonthly: 59000,
    priceOriginal: 89000,
    orderUrl: 'https://id.thuevpsgiare.vn/store/cloud-vps',
    features: [
      '1 vCPU Intel Xeon Gold',
      '1 GB RAM ECC tự sửa lỗi',
      '20 GB Ổ cứng NVMe U.2 Enterprise',
      'Băng thông 100 Mbps không giới hạn',
      '01 Địa chỉ IPv4 tĩnh riêng',
      'Full Root Access qua SSH',
      'Ảo hóa KVM độc lập tài nguyên',
      'Hạ tầng Datacenter Tier 3 tại Việt Nam',
    ],
  },
  {
    id: 'vps-gold-2',
    name: 'VPS Gold 2',
    cpu: '2 vCPU Intel Gold',
    ram: '2 GB RAM DDR4 ECC',
    disk: '35 GB SSD NVMe U.2',
    bandwidth: 'Unlimited Bandwidth',
    ipv4: '01 IPv4 Riêng',
    priceMonthly: 119000,
    priceOriginal: 169000,
    orderUrl: 'https://id.thuevpsgiare.vn/store/cloud-vps',
    features: [
      '2 vCPU Intel Xeon Gold',
      '2 GB RAM ECC tự sửa lỗi',
      '35 GB Ổ cứng NVMe U.2 Enterprise',
      'Băng thông 100 Mbps không giới hạn',
      '01 Địa chỉ IPv4 tĩnh riêng',
      'Full Root Access qua SSH',
      'Ảo hóa KVM độc lập tài nguyên',
      'Hạ tầng Datacenter Tier 3 tại Việt Nam',
    ],
  },
  {
    id: 'vps-gold-3',
    name: 'VPS Gold 3',
    badge: 'Phổ biến nhất',
    isPopular: true,
    cpu: '4 vCPU Intel Gold',
    ram: '4 GB RAM DDR4 ECC',
    disk: '60 GB SSD NVMe U.2',
    bandwidth: 'Unlimited Bandwidth',
    ipv4: '01 IPv4 Riêng',
    priceMonthly: 219000,
    priceOriginal: 319000,
    orderUrl: 'https://id.thuevpsgiare.vn/store/cloud-vps',
    features: [
      '4 vCPU Intel Xeon Gold',
      '4 GB RAM ECC tự sửa lỗi',
      '60 GB Ổ cứng NVMe U.2 Enterprise',
      'Băng thông 100 Mbps không giới hạn',
      '01 Địa chỉ IPv4 tĩnh riêng',
      'Full Root Access qua SSH',
      'Ảo hóa KVM độc lập tài nguyên',
      'Hạ tầng Datacenter Tier 3 tại Việt Nam',
      'Hỗ trợ kỹ thuật ưu tiên 24/7',
    ],
  },
  {
    id: 'vps-gold-4',
    name: 'VPS Gold 4',
    cpu: '6 vCPU Intel Gold',
    ram: '8 GB RAM DDR4 ECC',
    disk: '100 GB SSD NVMe U.2',
    bandwidth: 'Unlimited Bandwidth',
    ipv4: '01 IPv4 Riêng',
    priceMonthly: 419000,
    priceOriginal: 589000,
    orderUrl: 'https://id.thuevpsgiare.vn/store/cloud-vps',
    features: [
      '6 vCPU Intel Xeon Gold',
      '8 GB RAM ECC tự sửa lỗi',
      '100 GB Ổ cứng NVMe U.2 Enterprise',
      'Băng thông 100 Mbps không giới hạn',
      '01 Địa chỉ IPv4 tĩnh riêng',
      'Full Root Access qua SSH',
      'Ảo hóa KVM độc lập tài nguyên',
      'Hạ tầng Datacenter Tier 3 tại Việt Nam',
      'Hỗ trợ kỹ thuật ưu tiên 24/7',
    ],
  },
  {
    id: 'vps-gold-5',
    name: 'VPS Gold 5',
    cpu: '8 vCPU Intel Gold',
    ram: '16 GB RAM DDR4 ECC',
    disk: '160 GB SSD NVMe U.2',
    bandwidth: 'Unlimited Bandwidth',
    ipv4: '01 IPv4 Riêng',
    priceMonthly: 799000,
    priceOriginal: 1100000,
    orderUrl: 'https://id.thuevpsgiare.vn/store/cloud-vps',
    features: [
      '8 vCPU Intel Xeon Gold',
      '16 GB RAM ECC tự sửa lỗi',
      '160 GB Ổ cứng NVMe U.2 Enterprise',
      'Băng thông 100 Mbps không giới hạn',
      '01 Địa chỉ IPv4 tĩnh riêng',
      'Full Root Access qua SSH',
      'Ảo hóa KVM độc lập tài nguyên',
      'Hạ tầng Datacenter Tier 3 tại Việt Nam',
      'Hỗ trợ kỹ thuật chuyên sâu 24/7',
    ],
  },
];

export const BENCHMARK_ITEMS: BenchmarkItem[] = [
  {
    id: 'bench-sysinfo',
    title: 'System Information',
    imageUrl: 'https://thuevpsgiare.vn/wp-content/uploads/2026/08/system-information.png',
    metricLabel: 'Hạ tầng CPU',
    metricValue: 'Intel® Xeon® Gold',
    summary: 'Cấu hình phần cứng máy chủ vật lý doanh nghiệp với ảo hóa KVM chuẩn quốc tế.',
    details: [
      'CPU Intel Xeon Gold xung nhịp cao, tối ưu cho xử lý đa luồng',
      'Bộ nhớ RAM DDR4 ECC phát hiện và tự sửa lỗi bộ nhớ',
      'Ảo hóa phần cứng KVM đảm bảo tài nguyên cô lập hoàn toàn',
    ],
  },
  {
    id: 'bench-dd',
    title: 'Tốc độ Đọc/Ghi Ổ Đĩa (DD Test)',
    imageUrl: 'https://thuevpsgiare.vn/wp-content/uploads/2026/08/DD-information.png',
    metricLabel: 'Tốc độ I/O đĩa',
    metricValue: '1.5+ GB/s',
    summary: 'Ổ cứng Enterprise NVMe U.2 mang lại tốc độ truy xuất siêu tốc, gấp 5–7 lần SSD SATA thông thường.',
    details: [
      'Tốc độ đọc/ghi tuần tự cực cao, tối ưu hoá cho cơ sở dữ liệu MySQL/PostgreSQL',
      'Độ trễ truy xuất dữ liệu cực thấp (Microsecond Latency)',
      'IOPS vượt trội xử lý mượt mà hàng triệu truy vấn đồng thời',
    ],
  },
  {
    id: 'bench-speedtest',
    title: 'Kiểm tra Băng thông & Độ trễ (Speedtest)',
    imageUrl: 'https://thuevpsgiare.vn/wp-content/uploads/2026/08/speedtest-information.png',
    metricLabel: 'Độ trễ tại VN',
    metricValue: '1-20ms Ping',
    summary: 'Băng thông cổng mạng 100-200 Mbps không giới hạn lưu lượng, kết nối trực tiếp các nhà mạng lớn VNPT, Viettel, FPT.',
    details: [
      'Băng thông Uplink/Downlink ổn định 100-200 Mbps không bóp tốc độ',
      'Ping nội địa cực thấp (1–20ms nội địa)',
      'Tuyến cáp quang trực tiếp giúp tối ưu truy cập cho khách hàng trong nước',
    ],
  },
];

export const OS_DISTROS: OsDistro[] = [
  {
    id: 'ubuntu',
    name: 'Ubuntu Linux',
    tag: 'Phổ biến nhất',
    versions: ['24.04 LTS (Noble)', '22.04 LTS (Jammy)', '20.04 LTS (Focal)', '18.04 LTS (Bionic)'],
    description: 'Hệ điều hành phổ biến nhất cho web server, container Docker và môi trường lập trình hiện đại.',
  },
  {
    id: 'debian',
    name: 'Debian Linux',
    tag: 'Ổn định cao',
    versions: ['Debian 13.0 (Trixie)', 'Debian 12 (Bookworm)', 'Debian 11 (Bullseye)'],
    description: 'Nền tảng nổi tiếng về độ ổn định, tiêu thụ cực ít tài nguyên RAM, lý tưởng cho dịch vụ production.',
  },
  {
    id: 'almalinux',
    name: 'AlmaLinux OS',
    tag: 'Chuẩn Enterprise',
    versions: ['AlmaLinux 9.0 (Emerald)', 'AlmaLinux 8.10', 'AlmaLinux 8.7'],
    description: 'Bản phân phối thay thế hoàn hảo cho CentOS RHEL, tương thích nhị phân 1:1, hỗ trợ lâu dài.',
  },
  {
    id: 'centos',
    name: 'CentOS Linux',
    tag: 'Kinh điển',
    versions: ['CentOS 8.10 (Stream)', 'CentOS 8.2', 'CentOS 7.9'],
    description: 'Hệ điều hành doanh nghiệp quen thuộc, thích hợp cho các ứng dụng legacy và web control panels.',
  },
];

export const PARTNERS: Partner[] = [
  { id: 'p1', name: 'Proxmox VE', type: 'Nền tảng ảo hóa', logoId: 'proxmox' },
  { id: 'p2', name: 'KVM', type: 'Công nghệ ảo hóa', logoId: 'kvm' },
  { id: 'p3', name: 'Linux Foundation', type: 'Hệ sinh thái mã nguồn mở', logoId: 'linux' },
  { id: 'p4', name: 'Intel Xeon', type: 'Bộ xử lý máy chủ', logoId: 'intel' },
  { id: 'p5', name: 'AMD EPYC', type: 'Bộ xử lý máy chủ', logoId: 'amd' },
  { id: 'p6', name: 'Microsoft', type: 'Hệ điều hành máy chủ', logoId: 'microsoft' },
  { id: 'p7', name: 'VMware', type: 'Nền tảng ảo hóa', logoId: 'vmware' },
  { id: 'p8', name: 'Dell PowerEdge', type: 'Phần cứng máy chủ', logoId: 'dell' },
  { id: 'p9', name: 'Lenovo ThinkSystem', type: 'Phần cứng máy chủ', logoId: 'lenovo' },
  { id: 'p10', name: 'Supermicro', type: 'Phần cứng máy chủ', logoId: 'supermicro' },
  { id: 'p11', name: 'Samsung Enterprise', type: 'Lưu trữ doanh nghiệp', logoId: 'samsung' },
  { id: 'p12', name: 'HPE', type: 'Phần cứng máy chủ', logoId: 'hpe' },
];

export const FEEDBACKS: Feedback[] = [
  {
    id: 'fb-1',
    name: 'Nguyễn Hoàng Long',
    role: 'Lead Backend Developer',
    company: 'TechPlus Solutions',
    rating: 5,
    content: 'Mình chạy cụm microservices và database PostgreSQL trên gói VPS Gold 3 tại Fast Byte được hơn 6 tháng nay. Tốc độ đọc ghi NVMe U.2 thực sự rất ấn tượng, độ trễ cực thấp, hệ thống hoạt động liên tục 24/7 không gặp sự cố gián đoạn nào.',
    avatarText: 'NL',
  },
  {
    id: 'fb-2',
    name: 'Trần Minh Tuấn',
    role: 'Chủ chuỗi Shop Thời Trang Online',
    company: 'Tuấn Boutique',
    rating: 5,
    content: 'Website bán hàng WooCommerce của mình trước đây dùng hosting hay bị sập mỗi khi chạy flash sale quảng cáo. Chuyển sang thuê VPS giá rẻ tại Fast Byte với giá chỉ hơn 100k/tháng mà website tải nhanh tức thì, tỷ lệ chốt đơn tăng rõ rệt.',
    avatarText: 'TT',
  },
  {
    id: 'fb-3',
    name: 'Lê Phương Thảo',
    role: 'Giám đốc Kỹ thuật',
    company: 'Digital Alpha Agency',
    rating: 5,
    content: 'Agency của mình quản lý hơn 40 website vệ tinh cho khách hàng. Đăng ký VPS ở Fast Byte được cấp IPv4 tĩnh riêng, mạng trong nước ping chỉ 2–3ms, quy trình gia hạn và quản lý trên portal rất thuận tiện và minh bạch.',
    avatarText: 'PT',
  },
  {
    id: 'fb-4',
    name: 'Phạm Đức Anh',
    role: 'DevOps Engineer',
    company: 'Fintech Lab VN',
    rating: 5,
    content: 'Ưu điểm lớn nhất là Full Root Access, ảo hóa KVM chuẩn độc lập tài nguyên không bị oversell hay nghẽn CPU lúc cao điểm. Hạ tầng Intel Gold chạy Docker và CI/CD runner mượt mà vượt ngoài mong đợi trong tầm giá.',
    avatarText: 'ĐA',
  },
  {
    id: 'fb-5',
    name: 'Vũ Quốc Huy',
    role: 'Sinh viên CNTT & Nghiên cứu AI',
    company: 'Đại học Bách Khoa TP.HCM',
    rating: 5,
    content: 'Gói VPS Deal 59k/tháng cực kỳ phù hợp với túi tiền sinh viên tụi mình để thực hành triển khai web server Nginx, NodeJS và làm đồ án tốt nghiệp. Máy chủ khởi tạo tự động chỉ mất 2 phút sau khi thanh toán qua VNPAY.',
    avatarText: 'QH',
  },
  {
    id: 'fb-6',
    name: 'Đặng Mai Linh',
    role: 'Quản trị viên Hệ thống',
    company: 'VinaLogistics Corp',
    rating: 5,
    content: 'Hệ thống tracking nội bộ của công ty yêu cầu băng thông ổn định và uptime cao. Đội ngũ hỗ trợ kỹ thuật qua ticket của Fast Byte phản hồi rất nhanh và chuyên nghiệp, xử lý tận tình các thắc mắc về cấu hình mạng.',
    avatarText: 'ML',
  },
  {
    id: 'fb-7',
    name: 'Hoàng Văn Nam',
    role: 'Freelance Fullstack Dev',
    company: 'NamDev Studio',
    rating: 5,
    content: 'Mình đã test thử qua nhiều nhà cung cấp VPS giá rẻ tại Việt Nam, Fast Byte là nơi cho hiệu năng I/O ổ đĩa thực tế tốt nhất nhờ dùng dòng NVMe U.2 Enterprise chứ không phải SSD SATA cũ. Rất đáng đồng tiền bát gạo.',
    avatarText: 'VN',
  },
  {
    id: 'fb-8',
    name: 'Bùi Thị Bích Ngọc',
    role: 'Trưởng phòng Marketing',
    company: 'Sài Gòn EduTech',
    rating: 5,
    content: 'Chúng tôi triển khai hệ thống học trực tuyến Moodle trên VPS Fast Byte. Đường truyền mạng trong nước ổn định giúp học viên xem video bài giảng và thi trắc nghiệm trực tuyến mượt mà, không hề bị giật lag.',
    avatarText: 'BN',
  },
  {
    id: 'fb-9',
    name: 'Đỗ Hữu Trí',
    role: 'Nhà phát triển Ứng dụng Di động',
    company: 'GameApp Mobile',
    rating: 5,
    content: 'Server API của game mình cần khả năng phản hồi dưới 50ms cho người dùng trong nước. Đặt VPS ở datacenter Việt Nam của Fast Byte giúp ping luôn duy trì ở mức tối ưu 3-5ms. Rất hài lòng với dịch vụ.',
    avatarText: 'HT',
  },
  {
    id: 'fb-10',
    name: 'Ngô Thanh Sơn',
    role: 'CTO',
    company: 'CloudSaaS Vietnam',
    rating: 5,
    content: 'Fast Byte cung cấp hạ tầng phần cứng chuẩn Enterprise với mức giá vô cùng cạnh tranh. Đầy đủ hóa đơn GTGT điện tử, hợp đồng dịch vụ rõ ràng theo đúng pháp lý, rất yên tâm khi hợp tác lâu dài.',
    avatarText: 'TS',
  },
];

export const FAQS: FaqItem[] = [
  {
    id: 'faq-1',
    question: '1. VPS là gì, khác gì so với Web Hosting và Máy chủ vật lý riêng?',
    answer: 'VPS (Virtual Private Server - Máy chủ ảo cá nhân) được phân chia từ máy chủ vật lý bằng công nghệ ảo hóa (KVM). Khác với Web Hosting (nơi hàng trăm website dùng chung CPU, RAM và IP), VPS cung cấp cho bạn tài nguyên CPU/RAM độc lập 100%, 1 địa chỉ IPv4 tĩnh riêng và toàn quyền quản trị cao nhất (Root Access). So với máy chủ vật lý riêng, VPS linh hoạt hơn, chi phí tối ưu hơn gấp nhiều lần và có thể nâng cấp cấu hình tức thì trong vài phút mà không cần tháo lắp phần cứng.',
  },
  {
    id: 'faq-2',
    question: '2. VPS giá rẻ tại Fast Byte có bị bóp cấu hình hay chia sẻ tài nguyên với người khác không?',
    answer: 'Hoàn toàn không. Fast Byte sử dụng công nghệ ảo hóa phần cứng KVM (Kernel-based Virtual Machine) chuẩn quốc tế. Mọi tài nguyên CPU Intel Gold, RAM DDR4 ECC và dung lượng ổ cứng NVMe U.2 được cấp phát riêng biệt cho từng VPS. Hệ thống cam kết không oversell (bán vượt dung lượng thực), đảm bảo máy chủ của bạn luôn đạt 100% hiệu năng công bố kể cả trong giờ cao điểm.',
  },
  {
    id: 'faq-3',
    question: '3. Ổ cứng SSD NVMe U.2 tại Fast Byte nhanh hơn SSD thông thường như thế nào?',
    answer: 'SSD NVMe U.2 Enterprise là dòng ổ cứng chuẩn doanh nghiệp kết nối trực tiếp qua giao tiếp PCIe tốc độ cao, cho tốc độ đọc/ghi tuần tự lên tới 1.500 – 3.000 MB/s và chỉ số IOPS đạt hàng trăm nghìn thao tác/giây. Tốc độ này nhanh gấp 5 đến 7 lần so với ổ SSD SATA thông thường (chỉ ~500 MB/s) và nhanh gấp 20 lần so với HDD truyền thống, giúp website tải tức thì và cơ sở dữ liệu xử lý mượt mà.',
  },
  {
    id: 'faq-4',
    question: '4. Datacenter của Fast Byte đặt ở đâu và độ trễ (ping) tại Việt Nam là bao nhiêu?',
    answer: 'Hạ tầng máy chủ của Fast Byte được đặt tại các Trung tâm dữ liệu (Datacenter) đạt chuẩn quốc tế Tier 3 tại Việt Nam (Viettel IDC, VNPT Data). Do đặt trực tiếp trong nước, độ trễ (ping) đến người dùng tại Hà Nội, Đà Nẵng, TP.HCM chỉ từ 1 – 5ms, mang lại trải nghiệm truy cập cực nhanh và không bị ảnh hưởng mỗi khi xảy ra sự cố đứt cáp quang biển quốc tế.',
  },
  {
    id: 'faq-5',
    question: '5. Fast Byte cam kết thời gian hoạt động (Uptime) bao nhiêu và có SLA không?',
    answer: 'Fast Byte cam kết thời gian hoạt động mạng (Network Uptime) đạt 99.9% theo thỏa thuận dịch vụ (SLA). Hệ thống máy chủ được trang bị nguồn điện dự phòng UPS kép, máy phát điện diesel công nghiệp và hệ thống làm mát chính xác 24/7. Nếu thời gian gián đoạn vượt quá mức cam kết do lỗi hạ tầng, khách hàng sẽ được bồi thường theo đúng điều khoản SLA.',
  },
  {
    id: 'faq-6',
    question: '6. Tôi có được Full Root Access và toàn quyền cài đặt phần mềm không?',
    answer: 'Có, bạn nhận được 100% quyền quản trị cao nhất (Full Root Access qua SSH trên Linux). Bạn có thể tự do cài đặt mọi môi trường và phần mềm mong muốn như Docker, Nginx, Apache, Node.js, Python, Golang, MySQL, PostgreSQL, Redis, hoặc các Control Panel mã nguồn mở (CyberPanel, aaPanel, FastPanel, HestiaCP...).',
  },
  {
    id: 'faq-7',
    question: '7. VPS hỗ trợ các hệ điều hành nào?',
    answer: 'Fast Byte hỗ trợ cài đặt tự động hầu hết các bản phân phối Linux 64-bit phổ biến và mới nhất hiện nay, bao gồm: Ubuntu (24.04 LTS, 22.04 LTS, 20.04 LTS, 18.04 LTS), Debian (13.0, 12, 11), AlmaLinux (9.0, 8.10, 8.7), và CentOS (8.10, 8.2, 7.9). Bạn có thể tự thao tác cài lại hệ điều hành bất kỳ lúc nào trực tiếp trên trang quản trị dịch vụ.',
  },
  {
    id: 'faq-8',
    question: '8. Sau khi thanh toán, mất bao lâu để VPS được khởi tạo và bàn giao?',
    answer: 'Hệ thống Fast Byte được tích hợp cơ chế kích hoạt hoàn toàn tự động (Instant Provisioning). Ngay sau khi bạn hoàn tất thanh toán thành công qua VNPAY, mã QR ngân hàng hoặc cổng thanh toán trực tuyến, VPS sẽ được tự động tạo và gửi thông tin IP, Root Password về email của bạn chỉ sau 1 – 3 phút.',
  },
  {
    id: 'faq-9',
    question: '9. Fast Byte hỗ trợ những phương thức thanh toán nào?',
    answer: 'Chúng tôi hỗ trợ đa dạng phương thức thanh toán tự động và tiện lợi, bao gồm: Chuyển khoản ngân hàng 24/7 qua mã VietQR, Cổng thanh toán VNPAY (thẻ ATM nội địa, QR Pay ngân hàng, thẻ quốc tế Visa/MasterCard), và số dư ví trên portal id.thuevpsgiare.vn. Hóa đơn điện tử VAT được xuất tự động cho khách hàng doanh nghiệp.',
  },
  {
    id: 'faq-10',
    question: '10. Chính sách đổi trả và hoàn tiền của Fast Byte như thế nào?',
    answer: 'Theo chính sách dịch vụ của Fast Byte, khách hàng được xem xét hoàn tiền trong các trường hợp: (1) Không nhận được thông tin dịch vụ sau 03 ngày làm việc kể từ khi thanh toán thành công; (2) Dịch vụ bàn giao không đúng thông số kỹ thuật đã công bố; (3) Dịch vụ gặp lỗi kỹ thuật không ổn định từ 05 lần/ngày trở lên (đã xác thực qua ticket). Tiền hoàn sẽ được cộng vào tài khoản quản trị id.thuevpsgiare.vn trong vòng tối đa 30 ngày để sử dụng cho các dịch vụ khác.',
  },
  {
    id: 'faq-11',
    question: '11. Chính sách xử lý khiếu nại và cam kết thời gian phản hồi ra sao?',
    answer: 'Fast Byte luôn đề cao tinh thần hợp tác, thương lượng và hòa giải nhằm đảm bảo tối đa quyền lợi khách hàng. Đối với các khiếu nại liên quan đến chất lượng dịch vụ hoặc kỹ thuật, Fast Byte cam kết tiếp nhận và đưa ra phương án xử lý thỏa đáng chậm nhất trong vòng 24 giờ kể từ thời điểm tiếp nhận qua hệ thống ticket chính thức.',
  },
  {
    id: 'faq-12',
    question: '12. Tôi có thể nâng cấp gói VPS (CPU, RAM, Ổ cứng) trong quá trình sử dụng không?',
    answer: 'Có. Bạn có thể dễ dàng nâng cấp lên các gói cấu hình cao hơn bất kỳ lúc nào trực tiếp trên trang quản trị khách hàng. Hệ thống tự động tính toán chi phí chênh lệch theo số ngày còn lại của chu kỳ thanh toán. Toàn bộ dữ liệu, địa chỉ IP và cấu hình phần mềm hiện tại của bạn sẽ được giữ nguyên vẹn 100% khi nâng cấp.',
  },
  {
    id: 'faq-13',
    question: '13. Băng thông có thực sự Unlimited không, và cổng mạng (port speed) là bao nhiêu?',
    answer: 'Đúng vậy, mọi gói VPS tại Fast Byte đều được cấp băng thông truyền tải dữ liệu không giới hạn (Unlimited Bandwidth), không phụ thu phí truyền tải dữ liệu. Cổng mạng (Network Port) được thiết lập chuẩn 100 Mbps ổn định kết nối thẳng vào Core Router của Datacenter trong nước, đảm bảo đường truyền thông suốt cho mọi lưu lượng truy cập.',
  },
  {
    id: 'faq-14',
    question: '14. VPS có sẵn địa chỉ IPv4 riêng không, tôi có thể mua thêm IPv4 không?',
    answer: 'Mỗi gói VPS mặc định đều đi kèm 01 địa chỉ IPv4 tĩnh riêng biệt hoàn toàn (Dedicated Public IPv4), không chia sẻ với bất kỳ ai, sạch và uy tín cho việc gửi mail hay chạy web. Nếu có nhu cầu sử dụng nhiều IP cho mục đích riêng, bạn có thể liên hệ bộ phận hỗ trợ để đăng ký thêm IPv4 bổ sung.',
  },
  {
    id: 'faq-15',
    question: '15. Chính sách sao lưu (Backup) và an toàn dữ liệu được thực hiện thế nào?',
    answer: 'Fast Byte duy trì cơ chế bảo vệ phần cứng máy chủ với mảng RAID Enterprise nhằm chống hỏng hóc vật lý ổ đĩa. Tuy nhiên, theo quy định chung của dịch vụ máy chủ ảo không quản trị (Unmanaged VPS), khách hàng là người nắm giữ toàn quyền quản trị cao nhất và chịu trách nhiệm chính trong việc thiết lập lịch sao lưu dữ liệu quan trọng định kỳ của mình về nơi lưu trữ an toàn riêng.',
  },
  {
    id: 'faq-16',
    question: '16. Đội ngũ kỹ thuật hỗ trợ qua những kênh nào và trong thời gian bao lâu?',
    answer: 'Fast Byte duy trì đội ngũ hỗ trợ kỹ thuật 24/7/365 qua hệ thống gửi Ticket tại id.thuevpsgiare.vn/submitticket.php, Hotline 02873006198 và Email support@thuevpsgiare.vn. Các yêu cầu kỹ thuật phát sinh liên quan đến hạ tầng, kết nối mạng và hệ điều hành sẽ được phản hồi xử lý trong vòng 15 – 30 phút.',
  },
];
